Bump atlas to 0.39.0
GridTools/atlas4py pull request #23
Opened 2024-10-22 12:01 UTC by tehrengruber

2024-10-25 13:43 UTC, tehrengruber commented on src/atlas4py/CMakeLists.txt
> +    if(NOT TARGET copy_${ct_tgt})
This change just allows calling `copy_target` multiple times with the same argument.

2024-10-28 09:25 UTC, egparedes commented
Since the PR changes affect only CMake, I think @havogt is a better fit to review it.

2025-01-29 08:29 UTC, havogt requested changes
Didn't see this PR...

2025-01-29 08:29 UTC, havogt commented on src/atlas4py/CMakeLists.txt
> +                endif()
I think it's more consistent if we build the full list here and deduplicate. Now we are mixing patterns...

2025-01-29 08:29 UTC, havogt commented on src/atlas4py/_version.py
> +__version__ = "0.39.0.dev16"
```suggestion
__version__ = "0.39.0.dev0"
```
Why not restart from 0

2025-01-29 08:29 UTC, havogt commented on check_version.py
> +for l, p in zip(local_parts, pypi_parts):
I don't want to know what this script does...

2025-03-31 11:14 UTC, closed without merging

2025-03-31 11:14 UTC, havogt commented
Both changes are obsolete with #29